apiVersion: apps/v1
kind: Deployment
metadata:
  name: sched-scheduler-unit
  namespace: custom-scheduler
  labels:
    app: sched-scheduler-unit
    epsilon.queue: epsilon.distributed
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sched-scheduler-unit
      epsilon.queue: epsilon.distributed
  template:
    metadata:
      labels:
        app: sched-scheduler-unit
        epsilon.queue: epsilon.distributed
    spec:
      serviceAccountName: custom-scheduler
      containers:
      - name: sched-scheduler-unit
        image: alexnjh/epsilon_scheduler_service:0.0.2
        env:
        - name: MQ_HOST
          value: "sched-rabbitmq-0.sched-rabbitmq.custom-scheduler.svc.cluster.local"
        - name: MQ_PORT
          value: "5672"
        - name: MQ_USER
          value: "guest"
        - name: MQ_PASS
          value: "guest"
        - name: RECEIVE_QUEUE
          value: "epsilon.distributed"
        - name: RETRY_QUEUE
          value: "epsilon.backoff"
        # resources:
        #   limits:
        #     memory: "50M"
        #   requests:
        #     memory: "10M"
        ports:
